spring.application.name=inventory-service


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nirzarakushwah@gmail.com
spring.mail.password=whvp xryg ntmr ymxr

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
